version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "npm"
      include: "scope"
    reviewers:
      - "RobSpectre"
    assignees:
      - "RobSpectre"
    labels:
      - "dependencies"
      - "npm"
    # Group updates by dependency type
    groups:
      vue-ecosystem:
        patterns:
          - "vue*"
          - "@vue/*"
          - "vite*"
          - "@vitejs/*"
      testing:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "jsdom"
          - "@vue/test-utils"
      linting:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "lint-staged"
      build-tools:
        patterns:
          - "postcss*"
          - "autoprefixer"
          - "tailwindcss*"
      charts:
        patterns:
          - "echarts"
          - "reveal.js"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "RobSpectre"
    assignees:
      - "RobSpectre"
    labels:
      - "dependencies"
      - "github-actions"